name: Publish Artifacts

on:
  schedule:
    - cron: "20 2 * * 1"
  workflow_dispatch:

jobs:
  determine-versions:
    name: Determine versions to publish
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}

    steps:
      - uses: AshsWorkshop/actions/checkout@4b6fee62c3383c7c4a8b7878a74cce7707a98421 # main
        with:
          ref: ${{ github.ref_name }}

      - name: Get versions
        id: get_versions
        shell: bash
        run: |
          # Loop through all version builds
          output="["
          while IFS= read -r line; do
            # Extract from build version
            output="${output}\"${line%%_*}\", "
          done < <(grep -E "[0-9]+\.[0-9]+(?:\.[0-9]+)?_build=[0-9]+" gradle.properties)
          output="${output::-2}]"
          
          # Output list
          echo "versions=${output}" >> $GITHUB_OUTPUT

  publish:
    name: Publish ${{ matrix.versions }} artifacts
    needs:
      - determine-versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        versions: ${{ fromJSON(needs.determine-versions.outputs.versions) }}

    permissions:
      contents: write
      packages: write

    steps:
      - uses: AshsWorkshop/actions/checkout@4b6fee62c3383c7c4a8b7878a74cce7707a98421 # main
        with:
          ref: ${{ github.ref_name }}

      - name: Extract Java version
        id: extract_java
        shell: bash
        run: echo "java_version=$(grep 'java_version' gradle.properties | awk -F= '{$2=$2;print $2}')" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: AshsWorkshop/actions/setup-java@4b6fee62c3383c7c4a8b7878a74cce7707a98421 # main
        with:
          java-version: ${{ steps.extract_java.outputs.java_version }}
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: AshsWorkshop/actions/setup-gradle@4b6fee62c3383c7c4a8b7878a74cce7707a98421 # main
        with:
          add-job-summary: 'never'

      - name: Publish artifacts
        id: publish_artifacts
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UUID_USERNAME: ${{ secrets.UUID_USERNAME }}
          UUID_PASSWORD: ${{ secrets.UUID_PASSWORD }}
        run: |
          # Unpack transformers
          ./gradlew unpackTransformers -Pminecraft_version='${{ matrix.versions }}' 
          
          # Then generate and compute artifacts
          ./gradlew allTransformers -Pminecraft_version='${{ matrix.versions }}' 
          ./gradlew computeTransformerIntersection -Pminecraft_version='${{ matrix.versions }}' 
          
          # Finally check transformer hashes
          ./gradlew checkGeneratedTransformerHashes -Pminecraft_version='${{ matrix.versions }}' 
          
          # If compare file doesn't exist or the file contents are not the same
          if [[ ! -f "build/compare/${{ matrix.versions }}.json" ]] || (! cmp -s ".generated-hashes/${{ matrix.versions }}.json" "build/compare/${{ matrix.versions }}.json"); then
            # Publish artifacts
            ./gradlew publish -Pminecraft_version='${{ matrix.versions }}' 
          
            # Bump associated artifact version
            mod_build=$(grep '${{ matrix.versions }}_build' gradle.properties | awk -F= '{$2=$2;print $2}')
            echo "published_version=${{ matrix.versions }}.$mod_build" >> $GITHUB_OUTPUT
            mod_build=$(($mod_build + 1))
            sed -i "s/${{ matrix.versions }}_build=.*/${{ matrix.versions }}_build=$mod_build/" gradle.properties
          fi

      - name: Generate Gradle job summary
        uses: AshsWorkshop/actions/gradle-job-summary@3aa5f9872385230ad1ec446e3ed883081c0aeba8 # main

      - name: Commit ${{ matrix.versions }} and push branch
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            # Setup user settings
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

            # Commit files
            git add .
            git commit -a -m "chore([skip ci]): Action ${{ github.run_number }}: ${{ matrix.versions }} bumps"
            
            # Compute push
            versions_against=$(echo '${{ needs.determine-versions.outputs.versions }}' | jq '. | length')
            MAX_RETRIES=$((versions_against * 5))
            count=0
          
            # Handle if exit on error
            set +e
          
            until git push --force-with-lease -u origin ${{ github.ref_name }} || [ $count -eq $MAX_RETRIES ]; do
              ((count++))
              git fetch
              git merge -X theirs
            done
          
            set -e
          fi