name: Publish Artifacts

on:
  schedule:
    - cron: "20 2 * * 1"
  workflow_dispatch:

jobs:
  determine-versions:
    name: Determine versions to publish
    runs-on: ubuntu-latest

    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}

    steps:
      - uses: AshsWorkshop/actions/checkout@4b6fee62c3383c7c4a8b7878a74cce7707a98421 # main
        with:
          ref: ${{ github.ref_name }}

      - name: Get versions
        id: get_versions
        shell: bash
        run: |
          # Loop through all version builds
          output="["
          while IFS= read -r line; do
            # Extract from build version
            output="${output}\"${line%%_*}\", "
          done < <(grep -E "[0-9]+\.[0-9]+(?:\.[0-9]+)?_build=[0-9]+" gradle.properties)
          output="${output::-2}]"
          
          # Output list
          echo "versions=${output}" >> $GITHUB_OUTPUT

  publish:
    name: Publish ${{ matrix.versions }} artifacts
    needs:
      - determine-versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        versions: ${{ fromJSON(needs.determine-versions.outputs.versions) }}

    permissions:
      contents: write
      packages: write

    steps:
      - uses: AshsWorkshop/actions/checkout@4b6fee62c3383c7c4a8b7878a74cce7707a98421 # main
        with:
          ref: ${{ github.ref_name }}

      - name: Extract Java version
        id: extract_java
        shell: bash
        run: echo "java_version=$(grep 'java_version' gradle.properties | awk -F= '{$2=$2;print $2}')" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: AshsWorkshop/actions/setup-java@4b6fee62c3383c7c4a8b7878a74cce7707a98421 # main
        with:
          java-version: ${{ steps.extract_java.outputs.java_version }}
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: AshsWorkshop/actions/setup-gradle@4b6fee62c3383c7c4a8b7878a74cce7707a98421 # main
        with:
          add-job-summary: 'never'

      - name: Publish artifacts
        id: publish_artifacts
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UUID_USERNAME: ${{ secrets.UUID_USERNAME }}
          UUID_PASSWORD: ${{ secrets.UUID_PASSWORD }}
        run: |
          # Unpack transformers
          ./gradlew unpackTransformers -Pminecraft_version='${{ matrix.versions }}' 
          
          # Then generate and compute artifacts
          ./gradlew allTransformers -Pminecraft_version='${{ matrix.versions }}' 
          ./gradlew computeTransformerIntersection -Pminecraft_version='${{ matrix.versions }}' 
          
          # Finally check transformer hashes
          ./gradlew checkGeneratedTransformerHashes -Pminecraft_version='${{ matrix.versions }}' 
          
          # If compare file doesn't exist or the file contents are not the same
          VERSION_RELEASE=""
          if [[ ! -f "build/compare/${{ matrix.versions }}.json" ]] || (! cmp -s ".generated-hashes/${{ matrix.versions }}.json" "build/compare/${{ matrix.versions }}.json"); then
            # Publish artifacts
            ./gradlew publish -Pminecraft_version='${{ matrix.versions }}' 
          
            # Bump associated artifact version
            mod_build=$(grep '${{ matrix.versions }}_build' gradle.properties | awk -F= '{$2=$2;print $2}')
            VERSION_RELEASE="${{ matrix.versions }}.$mod_build"
            mod_build=$(($mod_build + 1))
            sed -i "s/${{ matrix.versions }}_build=.*/${{ matrix.versions }}_build=$mod_build/" gradle.properties
          fi
          # Report release version
          echo "published_version=$VERSION_RELEASE" >> $GITHUB_OUTPUT

      - name: Generate Gradle job summary
        uses: AshsWorkshop/actions/gradle-job-summary@0e8fad11c6fe005217c0440719523927df4d1e5f # main

      - name: Generate artifact example
        shell: bash
        run: |
          published_version="${{ steps.publish_artifacts.outputs.published_version }}"
          minecraft_version="${{ matrix.versions }}"
          echo "### Artifact Info" >> $GITHUB_STEP_SUMMARY
          # Check if a version was published
          if [ -n "$published_version" ]; then
            # Create template
            mkdir $RUNNER_TEMP/examples
            mdg_version="$(curl "https://maven.neoforged.net/api/maven/versions/releases/net/neoforged/moddev-gradle" | jq -r '.versions[-1]')"
            EXAMPLE_OUTPUT="$RUNNER_TEMP/examples/neoform.gradle.kts"
          
            export mdg_version
            export minecraft_version
            export published_version
            envsubst '$mdg_version $minecraft_version $published_version' < template/neoform.gradle.kts > $EXAMPLE_OUTPUT
            unset mdg_version
            unset minecraft_version
            unset published_version
            
            # Output info and example
            echo "**$published_version** has been successfully published!" >> $GITHUB_STEP_SUMMARY
            echo '```kotlin' >> $GITHUB_STEP_SUMMARY
            cat $EXAMPLE_OUTPUT >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            # Otherwise, display last version
            filter_mc_version=$minecraft_version
            if [ $(tr -dc '.' <<< $filter_mc_version | wc -c) -eq 1 ]; then
              filter_mc_version="${filter_mc_version}.0"
            fi
            published_version="$(curl "https://maven.uuid.gg/api/maven/versions/snapshots/net/ashwork/mc/transformers?filter=$filter_mc_version" | jq -r '.versions[-1]')"
            echo "No new releases. **$published_version** is still the latest version." >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY

      - name: Commit ${{ matrix.versions }} and push branch
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            # Setup user settings
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

            # Commit files
            git add .
            git commit -a -m "chore([skip ci]): Action ${{ github.run_number }}: ${{ matrix.versions }} bumps"
            
            # Compute push
            versions_against=$(echo '${{ needs.determine-versions.outputs.versions }}' | jq '. | length')
            MAX_RETRIES=$((versions_against * 5))
            count=0
          
            # Handle if exit on error
            set +e
          
            until git push --force-with-lease -u origin ${{ github.ref_name }} || [ $count -eq $MAX_RETRIES ]; do
              ((count++))
              git fetch
              git merge -X theirs
            done
          
            set -e
          fi